### ISSUE TITLE
Not working with mw 1.27.1 and php 7.0.8

### ISSUE THREAD

**Issue by rakekniven** [jonnylamb/simplefeed#2]
Just updated OS to Ubuntu 16.04 LTS server.

Now I get a white page when opening my wiki.
Apache error log says:
`[Thu Sep 01 09:43:58.663224 2016] [:error] [pid 9497] [client x.x.x.x:57416] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /<path>/mediawiki/extensions/simplepie.inc on line 738`

Before I had Ubuntu 12.04 LTS with mw 1.26.3 and php 5.5.x

What do I need to change?

Any help is appreciated.

**Comment by dennisroczek** [comment]
upgrade simplepie.inc which is not supported since ages. or switch to extension:rss as we did (for multiple reasons).

**Comment by rakekniven** [comment]
upgrading simplepie.inc is not possible for me. New versions of simplepie do not contain named file. It has been splitted into many small files and I am not able to make it work.

Switching to extension:rss does not work for me. Tried it last year with same result as now:
My screen layout has been messed up. I am using vector skin with default css. See attachment.

I am using default "MediaWiki:rss-feed" and "MediaWiki:rss-item".

Any idea?
![mediawiki-rss-screen-layout-mess](https://cloud.githubusercontent.com/assets/2069590/18308591/78e3badc-74f5-11e6-9e6d-5dd154e6b3e9.PNG)

**Comment by dennisroczek** [comment]
I know that updating simplepie.inc is not an option. Hence that was the reason why we did switch the extension.

Without having access to the wiki, I cannot help regarding extension:rss. I'm not having a problem. We only transclude bug reports (so IDs + Title of bug) and having no problem, see https://wiki.documentfoundation.org/WikiAction/edit/MediaWiki:Rss-feed

I really guess you have added or changed some div-tags and these produce some errors!

**Comment by rakekniven** [comment]
Closing.

**Comment by ernstki** [comment]
Download SimplePie 1.5 from https://www.simplepie.org/downloads and unpack the `1.5.zip` to the `extensions/SimplePie` directory, so that there's a `simplepie-1.5` directory alongside `SimpleFeed.php`. Bear in mind this library hasn't been updated since 2017, but sometimes software is just… done, like… WordStar for DOS.

Apply the following patch to `SimpleFeed.php`:

```diff
diff --git a/SimpleFeed.php b/SimpleFeed.php
index 607f730..0f9666d 100644
--- a/SimpleFeed.php
+++ b/SimpleFeed.php
@@ -32,7 +32,8 @@ if (!defined('MEDIAWIKI'))
 $wgSimpleFeed_Path = dirname( __FILE__ );
 $wgSimpleFeed_Cache = $wgSimpleFeed_Path . '/cache/';
 
-if ( ! @include($wgSimpleFeed_Path.'/simplepie.inc') )
+#if ( ! @include($wgSimpleFeed_Path.'/simplepie.inc') )
+if ( ! @require_once(__DIR__ . "/simplepie-1.5/autoloader.php") )
 {
        define('SIMPLEPIE_NOT_FOUND', true);
 }
@@ -63,7 +64,9 @@ function parseFeed($input, $args, $parser)
        global $wgSimpleFeed_Cache;
 
        // Disable page caching.
-       $parser->disableCache();
+       /* $parser->disableCache(); */
+       // https://www.mediawiki.org/wiki/Extensions_FAQ#How_do_I_disable_caching_for_pages_using_my_extension?
+       $parser->getOutput()->updateCacheExpiry(0);
        
        // Check to see whether SimplePie was actually included.
        if (defined('SIMPLEPIE_NOT_FOUND'))
```

You can either manually make those changes, or (assuming you're on a reasonably well-equipped *nix system) save the above diff to a file and then `patch -p1 < thefilename` while you're in the same directory as `SimplePie.php`.

Tested with PHP 7.4.x and MediaWiki 1.35.x. I'll try to remember to update this comment if any problems crop up in the future.

Hope that helps.
